name: nightly
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make all BUILD_TYPE=Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: ./build/
        if-no-files-found: error

  mac-x86_64:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make all BUILD_TYPE=Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mac-x86_64
        path: ./build/
        if-no-files-found: error

  netbsd-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run NetBSD VM & Build
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        prepare: |
          /usr/sbin/pkg_add gmake

        run: |
          gmake all BUILD_TYPE=Release CC=gcc

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: netbsd-x86_64
        path: ./build/
        if-no-files-found: error

  freebsd-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run FreeBSD VM & Build
      id: termrec
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y gmake

        run: |
          gmake all BUILD_TYPE=Release CC=clang

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: freebsd-x86_64
        path: ./build/
        if-no-files-found: error

  openbsd-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run OpenBSD VM & Build
      id: termrec
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg_add gmake

        run: |
          gmake all BUILD_TYPE=Release CC=clang

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openbsd-x86_64
        path: ./build/
        if-no-files-found: error

  update-ci-release:
    needs: [linux-x86_64, mac-x86_64, netbsd-x86_64, freebsd-x86_64, openbsd-x86_64]
    permissions:
      contents: write
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        tag_name: nightly
        delete_release: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/download-artifact@v3
      with:
        name: linux-x86_64
        path: ./linux-x86_64/

    - uses: actions/download-artifact@v3
      with:
        name: openbsd-x86_64
        path: ./openbsd-x86_64/

    - uses: actions/download-artifact@v3
      with:
        name: freebsd-x86_64
        path: ./freebsd-x86_64/

    - uses: actions/download-artifact@v3
      with:
        name: netbsd-x86_64
        path: ./netbsd-x86_64/

    - uses: actions/download-artifact@v3
      with:
        name: mac-x86_64
        path: ./mac-x86_64/

    - name: Rename
      run: |
        mv ./linux-x86_64/termrec ./termrec-linux-x86_64
        mv ./freebsd-x86_64/termrec ./termrec-freebsd-x86_64
        mv ./openbsd-x86_64/termrec ./termrec-openbsd-x86_64
        mv ./netbsd-x86_64/termrec ./termrec-netbsd-x86_64
        mv ./osx-x86_64/termrec ./termrec-osx-x86_64

    - uses: ncipollo/release-action@v1
      with:
        name: "Termrec dev build"
        body: "this release is not for daily use."
        tag: "nightly"
        commit: "master"
        prerelease: true
        allowUpdates: true
        generateReleaseNotes: true
        artifactErrorsFailBuild: true
        artifacts: |
          ./termrec-linux-x86_64
          ./termrec-freebsd-x86_64
          ./termrec-openbsd-x86_64
          ./termrec-netbsd-x86_64
          ./termrec-osx-x86_64

