name: nightly
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make all

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: ./build/
        if-no-files-found: error

  mac-x86_64:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make all

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mac-x86_64
        path: ./build/
        if-no-files-found: error

  freebsd-x86_64:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run FreeBSD VM & Build
      id: termrec
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg install -y gmake git

        run: |
          gmake all

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: feeebsd-x86_64
        path: ./build/
        if-no-files-found: error

  openbsd-x86_64:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run OpenBSD VM & Build
      id: termrec
      uses: vmactions/openbsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg_add gmake

        run: |
          gmake all

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openbsd-x86_64
        path: ./build/
        if-no-files-found: error

